---
applications:
  - memory: 1024m
    health-check-type: process
    docker:
      image: registry.mzdev.kr/IMAGE_PROJECT/IMAGE_NAME:IMAGE_TAG
    command: java $JAVA_OPTS -jar ./app.jar
    env:
      JAVA_OPTS: RUNTIME_OPTIONS
    routes:
    - route: run.mzdev.kr
    - route: work-v1.apps.awsprd.mzdev.kr